modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://www.github.com/xfacthd/framedblocks"
license="LGPL v3"

[[mods]]
    modId="framedblocks"
    version="${mod_version}"
    displayName="FramedBlocks"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/framedblocks"
    logoFile="logo.png"
    logoBlur=false
    authors="XFactHD"
    description='''Fancy building blocks'''



[[mixins]]
    config="framedblocks.mixin.json"



[[dependencies.framedblocks]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="athena"
    type="optional"
    versionRange="[${athena_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.framedblocks]]
    modId="atlasviewer"
    type="optional"
    versionRange="[${atlasviewer_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.framedblocks]]
    modId="buildinggadgets"
    type="optional"
    versionRange="[${buildinggadgets_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="contex"
    type="optional"
    versionRange="[${contex_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.framedblocks]]
    modId="ctm"
    type="optional"
    versionRange="[${ctm_version},)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.framedblocks]]
    modId="create"
    type="optional"
    versionRange="[${create_version},)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.framedblocks]]
    modId="diagonalblocks"
    type="optional"
    versionRange="[${diag_blocks_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="emi"
    type="optional"
    versionRange="[${emi_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="jei"
    type="optional"
    versionRange="[${jei_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="modernfix"
    type="optional"
    versionRange="[${modernfix_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.framedblocks]]
    modId="nocubes"
    type="optional"
    versionRange="[${nocubes_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.framedblocks]]
    modId="rei"
    type="optional"
    versionRange="[${rei_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="supplementaries"
    type="optional"
    versionRange="[${supplementaries_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="ae2"
    type="optional"
    versionRange="[${ae2_version},)"
    ordering="NONE"
    side="BOTH"



[mods."modernfix:integration"]
    client_entrypoint="xfacthd.framedblocks.common.compat.modernfix.FramedModernFixClientIntegration"
